#!/usr/bin/env python3
"""generate_orphans.py — Generiert docs/_generated/orphans.md.

Identifiziert Markdown-Dateien, die von keiner anderen Datei
über Frontmatter-Relationen referenziert werden.

Ausgabe: docs/_generated/orphans.md
"""

import sys
from pathlib import Path

# Gemeinsame Pfad-Logik aus _paths.py
sys.path.insert(0, str(Path(__file__).parent))
from _paths import should_skip, write_if_changed, extract_frontmatter, resolve_relation_target  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "orphans.md"

# Dokumente, die als Wurzeln behandelt werden und keine eingehenden Referenzen benötigen
ROOT_FILES = {
    "README.md",
    "CONTRIBUTING.md",
    "AGENTS.md",
    "docs/foundations/vision.md",
    "docs/foundations/repo-plan.md",
    "docs/index.md",
    "docs/masterplan.md",
    "docs/policies/privacy-and-ethics.md",
    "benchmarks/challenges/rest-api-v1.md",
    "benchmarks/challenges/kanban-board-v1.md",
    "benchmarks/challenges/legacy-refactoring-v1.md",
}


def collect_unreferenced(repo_root: Path) -> set[str]:
    """Return repo-relative paths of markdown files not referenced by any other file.

    Fragment-suffixes in targets (e.g. ``file.md#section``) are stripped before
    path resolution so that ``target.md`` is counted as referenced, not
    ``target.md#section`` (a non-existent path).
    Root files (README etc.) are excluded from the result.
    """
    all_docs: set[str] = set()
    referenced: set[str] = set()

    for md_file in sorted(repo_root.rglob("*.md")):
        if should_skip(md_file, repo_root, skip_generated=True):
            continue
        if "_template" in md_file.relative_to(repo_root).parts:
            continue

        rel_path = str(md_file.relative_to(repo_root))
        all_docs.add(rel_path)

        fm = extract_frontmatter(md_file)
        if fm is None or "relations" not in fm:
            continue

        for rel in fm.get("relations", []):
            if not isinstance(rel, dict):
                continue
            target = rel.get("target", "")
            if not isinstance(target, str) or target.startswith("#"):
                continue
            resolved = resolve_relation_target(md_file, target, repo_root)
            if resolved is None:
                continue
            try:
                ref_path = str(resolved.relative_to(repo_root))
                referenced.add(ref_path)
            except ValueError:
                pass

    return all_docs - referenced - ROOT_FILES


def main():
    orphans = sorted(collect_unreferenced(REPO_ROOT))

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        "<!-- Generated by generate_orphans.py -->",
        "",
        "# Unreferenced Documents",
        "",
        f"Documents not referenced by any other document via frontmatter relations ({len(orphans)} found):",
        "",
    ]

    if orphans:
        for orphan in orphans:
            lines.append(f"- `{orphan}`")
    else:
        lines.append("*No unreferenced documents found.*")

    lines.append("")
    content = "\n".join(lines)
    written = write_if_changed(OUTPUT, content)
    status_sym = "✅" if written else "✔️ (unchanged)"
    print(f"{status_sym} Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(orphans)} unreferenced)")


if __name__ == "__main__":
    main()
