#!/usr/bin/env python3
"""generate_metrics.py - Generate a small metrics trend report from evidence.jsonl.

This generator is intentionally minimal and is gated by system decisions.
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
EXPERIMENTS_DIR = REPO_ROOT / "experiments"
OUTPUT_PATH = REPO_ROOT / "docs" / "_generated" / "metrics" / "trends.md"

MIN_EVENTS = 20
MIN_EVENT_TYPES = 3


def _to_float(value: object) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _read_entries() -> tuple[list[dict], list[str]]:
    entries: list[dict] = []
    source_paths: list[str] = []

    for evidence_file in sorted(EXPERIMENTS_DIR.glob("*/results/evidence.jsonl")):
        exp_dir = evidence_file.parent.parent
        if exp_dir.name.startswith("_"):
            continue

        rel = evidence_file.relative_to(REPO_ROOT).as_posix()
        source_paths.append(rel)

        for lineno, raw_line in enumerate(evidence_file.read_text(encoding="utf-8").splitlines(), start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSON in {rel}:{lineno}: {exc}") from exc

            if not isinstance(entry, dict):
                raise ValueError(f"expected JSON object in {rel}:{lineno}")

            entry["_source"] = rel
            entries.append(entry)

    return entries, source_paths


def _build_report(entries: list[dict], source_paths: list[str]) -> str:
    by_event_type = Counter()
    by_metric_count = Counter()
    by_metric_numeric: dict[str, list[float]] = defaultdict(list)

    for entry in entries:
        event_type = str(entry.get("event_type", "unknown"))
        metric = str(entry.get("metric", "unknown"))
        by_event_type[event_type] += 1
        by_metric_count[metric] += 1
        num = _to_float(entry.get("value"))
        if num is not None:
            by_metric_numeric[metric].append(num)

    distinct_event_types = sorted(by_event_type.keys())

    lines: list[str] = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        "<!-- Generated by scripts/docmeta/generate_metrics.py -->",
        "",
        "# Metrics Trends (Pilot)",
        "",
        f"Generated: {date.today().isoformat()}",
        "",
        "## Gate Snapshot",
        "",
        f"- Total events: **{len(entries)}**",
        f"- Distinct event types: **{len(distinct_event_types)}** ({', '.join(distinct_event_types)})",
        f"- Source evidence files: **{len(source_paths)}**",
        "",
        "## Event Type Counts",
        "",
        "| event_type | events |",
        "| --- | ---: |",
    ]

    for event_type in sorted(by_event_type):
        lines.append(f"| {event_type} | {by_event_type[event_type]} |")

    lines.extend([
        "",
        "## Metric Aggregates",
        "",
        "| metric | events | numeric_samples | min | max | median |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ])

    for metric in sorted(by_metric_count):
        numeric = by_metric_numeric.get(metric, [])
        if numeric:
            min_v = f"{min(numeric):.3g}"
            max_v = f"{max(numeric):.3g}"
            median_v = f"{statistics.median(numeric):.3g}"
        else:
            min_v = "-"
            max_v = "-"
            median_v = "-"
        lines.append(
            f"| {metric} | {by_metric_count[metric]} | {len(numeric)} | {min_v} | {max_v} | {median_v} |"
        )

    lines.extend([
        "",
        "## Source Paths",
        "",
    ])
    lines.extend(f"- `{p}`" for p in source_paths)
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    entries, source_paths = _read_entries()

    if len(entries) < MIN_EVENTS:
        print(f"❌ Metrics gate failed: need at least {MIN_EVENTS} events, found {len(entries)}")
        return 1

    distinct_event_types = {str(e.get("event_type", "unknown")) for e in entries}
    if len(distinct_event_types) < MIN_EVENT_TYPES:
        print(
            "❌ Metrics gate failed: "
            f"need at least {MIN_EVENT_TYPES} event types, found {len(distinct_event_types)}"
        )
        return 1

    report = _build_report(entries, source_paths)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(report, encoding="utf-8")
    print(f"✅ Generated {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
