#!/usr/bin/env python3
"""generate_system_map.py — Generiert docs/_generated/system-map.md.

Erzeugt eine Systemübersicht: Welche Ordner existieren, wie viele
Dokumente sie enthalten, und welcher Zone sie zugehören.

Ausgabe: docs/_generated/system-map.md
"""

import sys
from pathlib import Path

# Gemeinsame Pfad-Logik aus _paths.py
sys.path.insert(0, str(Path(__file__).parent))
from _paths import SKIP_DIR_NAMES, write_if_changed  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "system-map.md"

ZONE_MAP = {
    "experiments": "🔬 Labor",
    "catalog": "📚 Bibliothek",
    "prompts": "📚 Bibliothek",
    "benchmarks": "📚 Bibliothek",
    "instruction-blocks": "📚 Bibliothek",
    "exports": "⚙️ Generiert",
    "docs/_generated": "⚙️ Generiert",
    ".cursor": "⚙️ Generiert",
    "contracts": "🏛️ Governance",
    "schemas": "🏛️ Governance",
    "decisions": "🏛️ Governance",
    ".vibe": "🏛️ Governance",
    "docs": "📖 Dokumentation",
    "scripts": "🔧 Tooling",
    "tools": "🔧 Tooling",
}


def get_zone(key: str) -> str:
    return ZONE_MAP.get(key, "📁 Root")


def classify_top_dir(rel: str) -> str:
    """Bestimmt den Gruppierungsschlüssel für eine Datei.

    docs/_generated/* wird als eigene Gruppe ausgegeben (Zone: Generiert),
    nicht im docs/-Aggregat versteckt.
    """
    parts = rel.split("/")
    if len(parts) >= 2 and parts[0] == "docs" and parts[1] == "_generated":
        return "docs/_generated"
    if len(parts) > 1:
        return parts[0]
    return "."


def main():
    dir_stats: dict[str, dict] = {}

    for item in sorted(REPO_ROOT.rglob("*")):
        rel_parts = item.relative_to(REPO_ROOT).parts
        # Skip .git, .github, .cursor, node_modules, __pycache__ — but NOT .vibe
        if any(p in SKIP_DIR_NAMES for p in rel_parts):
            continue
        if not item.is_file():
            continue

        rel = str(item.relative_to(REPO_ROOT))
        key = classify_top_dir(rel)

        if key not in dir_stats:
            dir_stats[key] = {"files": 0, "md_files": 0, "zone": get_zone(key)}
        dir_stats[key]["files"] += 1
        if item.suffix == ".md":
            dir_stats[key]["md_files"] += 1

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        "<!-- Generated by generate_system_map.py -->",
        "",
        "# System Map",
        "",
        "| Directory | Zone | Files | Markdown |",
        "| --------- | ---- | ----: | -------: |",
    ]

    for dir_name in sorted(dir_stats.keys()):
        stats = dir_stats[dir_name]
        lines.append(f"| `{dir_name}/` | {stats['zone']} | {stats['files']} | {stats['md_files']} |")

    lines.append("")
    lines.append(f"**Total:** {sum(s['files'] for s in dir_stats.values())} files in {len(dir_stats)} directories")
    lines.append("")

    content = "\n".join(lines)
    written = write_if_changed(OUTPUT, content)
    status_sym = "✅" if written else "✔️ (unchanged)"
    print(f"{status_sym} Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(dir_stats)} directories)")


if __name__ == "__main__":
    main()
