#!/usr/bin/env python3
"""Generate a non-authoritative experiment-state snapshot.

The output is an artifact-only diagnostic. It mirrors manifest state and keeps
only two bounded heuristics: structural design coverage and interpretation-risk
signals. It never changes experiment truth or authorizes adoption.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _paths import write_if_changed  # noqa: E402

try:
    import yaml
except ImportError:
    print("ERROR: Missing dependency. Run: pip install pyyaml")
    raise SystemExit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
EXPERIMENTS_DIR = REPO_ROOT / "experiments"
OUTPUT = REPO_ROOT / "docs" / "_generated" / "epistemic-state.md"
CONTENT_THRESHOLD = 300


def load_manifest(path: Path) -> dict:
    """Load one manifest and reject non-mapping structures."""
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"manifest root must be a mapping/object, got {type(data).__name__}")
    experiment = data.get("experiment")
    if experiment is not None and not isinstance(experiment, dict):
        raise ValueError(
            f"manifest.experiment must be a mapping/object, got {type(experiment).__name__}"
        )
    return data


def derive_design_quality(exp_dir: Path) -> str:
    """Return structured, partial, or minimal from two design documents."""
    substantial = [
        (exp_dir / name).is_file() and (exp_dir / name).stat().st_size > CONTENT_THRESHOLD
        for name in ("method.md", "failure_modes.md")
    ]
    if all(substantial):
        return "structured"
    if any(substantial):
        return "partial"
    return "minimal"


def _has_parseable_evidence(exp_dir: Path) -> bool:
    path = exp_dir / "results" / "evidence.jsonl"
    if not path.is_file():
        return False
    try:
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            if raw_line.strip():
                json.loads(raw_line)
                return True
    except (OSError, UnicodeError, json.JSONDecodeError):
        return False
    return False


def _has_interpretation_budget(exp_dir: Path) -> bool:
    path = exp_dir / "results" / "result.md"
    try:
        return path.is_file() and "## Interpretation Budget" in path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False


def derive_interpretation_risk(exp_dir: Path, manifest: dict) -> str:
    """Apply the existing six-signal heuristic and return low, medium, or high."""
    experiment = manifest.get("experiment", {})
    status = experiment.get("status", "")
    execution = experiment.get("execution_status", "")
    evidence_level = experiment.get("evidence_level", "")
    adoption_basis = experiment.get("adoption_basis", "")

    signals = (
        not _has_parseable_evidence(exp_dir),
        execution in {"reconstructed", "designed", "prepared"},
        evidence_level in {"anecdotal", ""} or evidence_level is None,
        adoption_basis in {"executed", "replicated"} and adoption_basis != execution,
        status == "adopted" and not _has_interpretation_budget(exp_dir),
        status == "adopted"
        and (
            not (exp_dir / "results" / "decision.yml").is_file()
            or execution not in {"executed", "replicated", "reconstructed"}
        ),
    )
    count = sum(signals)
    if count <= 1:
        return "low"
    if count <= 3:
        return "medium"
    return "high"


def collect_rows(experiments_dir: Path = EXPERIMENTS_DIR) -> tuple[list[dict[str, str]], list[str]]:
    """Collect deterministic rows and fail-loud manifest errors."""
    rows: list[dict[str, str]] = []
    errors: list[str] = []
    for manifest_path in sorted(experiments_dir.glob("*/manifest.yml")):
        exp_dir = manifest_path.parent
        if exp_dir.name.startswith("_"):
            continue
        try:
            manifest = load_manifest(manifest_path)
        except Exception as exc:
            errors.append(f"  ❌ {manifest_path}: {exc}")
            continue
        experiment = manifest.get("experiment", {})
        rows.append(
            {
                "name": exp_dir.name,
                "status": experiment.get("status", "—"),
                "design_quality": derive_design_quality(exp_dir),
                "execution_state": experiment.get("execution_status", "—"),
                "evidence_strength": experiment.get("evidence_level", "—"),
                "interpretation_risk": derive_interpretation_risk(exp_dir, manifest),
            }
        )
    return rows, errors


def render_report(rows: list[dict[str, str]]) -> str:
    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        "<!-- Generated by generate_epistemic_state.py -->",
        "",
        "# Epistemic State — Experiment-Übersicht",
        "",
        "> Artifact-only Diagnose. Alle Werte sind gespiegelt oder heuristisch abgeleitet;",
        "> dieses Dokument ist keine Wahrheitsquelle und autorisiert keine Entscheidung.",
        "",
        "| Experiment | Status | Design Quality | Execution State | Evidence Strength | Interpretation Risk |",
        "| ---------- | ------ | -------------- | --------------- | ----------------- | ------------------- |",
    ]
    for row in rows:
        lines.append(
            f"| `{row['name']}` | {row['status']} | {row['design_quality']} | "
            f"{row['execution_state']} | {row['evidence_strength']} | {row['interpretation_risk']} |"
        )
    lines.extend(
        [
            "",
            "## Grenze",
            "",
            "- `design_quality` prüft nur Dateivorhandensein und Mindestgröße.",
            "- `interpretation_risk` zählt sechs vorhandene Struktur- und Konsistenzsignale.",
            "- Inhaltliche Qualität, Kausalität und Nutzen werden nicht bewertet.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    rows, errors = collect_rows()
    if errors:
        print("❌ Manifest-Ladefehler — Report wird nicht geschrieben:")
        for error in errors:
            print(error)
        return 1
    written = write_if_changed(OUTPUT, render_report(rows))
    symbol = "✅" if written else "✔️ (unchanged)"
    print(f"{symbol} Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(rows)} experiments)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
