#!/usr/bin/env python3
"""generate_orphans.py — Generiert docs/_generated/orphans.md.

Identifiziert Markdown-Dateien, die von keiner anderen Datei
über Frontmatter-Relationen referenziert werden.

Ausgabe: docs/_generated/orphans.md
"""

import sys
from pathlib import Path

# Gemeinsame Pfad-Logik aus _paths.py
sys.path.insert(0, str(Path(__file__).parent))
from _paths import should_skip, write_if_changed, extract_frontmatter  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "orphans.md"

# Dokumente, die als Wurzeln behandelt werden und keine eingehenden Referenzen benötigen
ROOT_FILES = {
    "README.md",
    "CONTRIBUTING.md",
    "AGENTS.md",
    "vision.md",
    "repo-plan.md",
    "docs/index.md",
    "docs/masterplan.md",
    "docs/policies/privacy-and-ethics.md",
    "benchmarks/challenges/rest-api-v1.md",
}


def main():
    all_docs: set[str] = set()
    referenced: set[str] = set()

    for md_file in sorted(REPO_ROOT.rglob("*.md")):
        if should_skip(md_file, REPO_ROOT, skip_generated=True):
            continue
        if "_template" in md_file.relative_to(REPO_ROOT).parts:
            continue

        rel_path = str(md_file.relative_to(REPO_ROOT))
        all_docs.add(rel_path)

        fm = extract_frontmatter(md_file)
        if fm is None or "relations" not in fm:
            continue

        for rel in fm.get("relations", []):
            if not isinstance(rel, dict):
                continue
            target = rel.get("target", "")
            if target.startswith("#"):
                continue
            resolved = (md_file.parent / target).resolve()
            try:
                ref_path = str(resolved.relative_to(REPO_ROOT))
                referenced.add(ref_path)
            except ValueError:
                pass

    orphans = sorted(all_docs - referenced - ROOT_FILES)

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        "<!-- Generated by generate_orphans.py -->",
        "",
        "# Unreferenced Documents",
        "",
        f"Documents not referenced by any other document via frontmatter relations ({len(orphans)} found):",
        "",
    ]

    if orphans:
        for orphan in orphans:
            lines.append(f"- `{orphan}`")
    else:
        lines.append("*No unreferenced documents found.*")

    lines.append("")
    content = "\n".join(lines)
    written = write_if_changed(OUTPUT, content)
    status_sym = "✅" if written else "✔️ (unchanged)"
    print(f"{status_sym} Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(orphans)} unreferenced)")


if __name__ == "__main__":
    main()
